apiVersion: v1
kind: Namespace
metadata:
  name: fggdfdfggdf-dev
  labels:
    environment-id: env_9f27e2d8-2380-4213-8482-202813c68f12
    project-id: project_377a0887-086b-4635-a64a-c575572116ee
    project-name: fggdfdfggdf
    environment-name: dev
    organization-id: org_2f580e67-b29e-4f1b-b2d6-dc1a15300182
